name: oppa_tmdb
description: "A new Flutter project."
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  transparent_image: ^2.0.1
  dio: ^5.3.4
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  envied: ^0.5.2
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  intl: ^0.19.0

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  riverpod_generator: ^2.3.9
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  envied_generator: ^0.5.2
  
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/